export const REGISTER_USER = "REGISTER_USER"
export const LOGIN_USER = "LOGIN_USER"
export const LOGOUT_USER = "LOGOUT_USER"
export const SET_IS_LOADING = "SET_IS_LOADING"
export const SET_USER = "SET_USER"
export const SET_DATE = "SET_DATE"
